SELECT * FROM Student
WHERE FirstName = 'Antonio'

SELECT * FROM Student
WHERE DateOfBirth > '01.01.1999'

SELECT * FROM STUDENT
WHERE LastName like 'J%' and (EnrolledDate between '01.01.1998' and '01.02.1998')

SELECT * FROM STUDENT
ORDER BY FirstName ASC

SELECT LastName FROM TEACHER ​
UNION
SELECT LastName FROM STUDENT 

ALTER TABLE GRADE WITH NOCHECK
ADD CONSTRAINT FK_GRADE_StudentID
Foreign key (StudentID)
REFERENCES STUDENT (Id)

SELECT COURSE.Name, ACHIEVEMENTTYPE.Name from COURSE 
  CROSS JOIN ACHIEVEMENTTYPE

SELECT * FROM TEACHER
LEFT JOIN GRADE
ON TEACHER.Id = GRADE.TeacherId  
WHERE GRADE.TeacherId is null